---
- name: "Installing and Configuring Mariadb"
  hosts: test
  become: true
  vars_files:
    - vars.yml
  tasks:
        
    - name: "Mariadb - Installing Package"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present
            
            
    - name: "Mariadb - Restating/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
            

    - name: "Mariadb - Update Root Password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root }}"
        host_all: true


    - name: "Mariadb - Deleting Anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        user: ""
        host_all: true
        state: absent
