---
- name: "Installing and Configuring Mariadb"
  hosts: test
  become: true
  vars_files:
    - vars.yml
  tasks:
        
    - name: "Mariadb - Installing Package"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present
            
            
    - name: "Mariadb - Restating/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
            
